### PR TITLE
Refactor results client; Add auto start server

### PR DESCRIPTION
**Pull request by samparent97**
- [x]  Check that this works on windows
- [x]  Check that we dont get orphan process on panic

### CODE REVIEW

**Comment by TylerStAmour** [comment]
Seems to be working fine on my machine. Maybe we should create some unit tests for it too then?

**Comment by samparent97** [comment]
Yea wouldn't be a bad idea, let's leave it for a future PR.

**Review by TylerStAmour — DISMISSED** [review]

**Review by hsidd1 — CHANGES_REQUESTED** [review]
Change `_python3` const for windows !!

**Review by hsidd1 — APPROVED** [review]
#### Works and auto starts server on Windows
 We might need to look into Complete Test issue again though (sep issue)

**Pull request merged**
