### PR TITLE
CAN Client Implementation

### PR DESCRIPTION
**Pull request by TylerStAmour**

### CODE REVIEW

**Review by itshady — APPROVED** [review]
Add the test you ran here in the cmd/ folder

**Comment by TylerStAmour** [comment]
> Add the test you ran here in the cmd/ folder

Good idea, added it

**Comment by itshady** [comment]
@TylerStAmour I just realized, for the test as well, we should add a call with Read() that passes in messages to read back

**Comment by TylerStAmour** [comment]
> @TylerStAmour I just realized, for the test as well, we should add a call with Read() that passes in messages to read back

Added. The tracking functions should take care of testing Read() calls with no passed messages now

**Comment by TylerStAmour** [comment]
@samparent97 good to merge?

**Review by itshady — APPROVED** [review]

**Pull request merged**
